version: '3.0'

services:
  mongo:
    container_name: mongo
    image: mongo
    ports:
      - 27017:27017
    restart: always
  server:
    container_name: server
    build:
      context: ./
      dockerfile: src/server/Dockerfile
    env_file:
      - .env
    volumes:
      - ./server/:/auth-ts/src/server
      - ./node_modules
    ports:
      - 5000:5000
    command: npm run start
    depends_on:
      - mongo
    restart: always
  client:
      container_name: client
      build:
        context: ./src/client
        dockerfile: Dockerfile
      ports:
        - 3000:3000
      command: npm run deploy
      depends_on:
        - server
      restart: always
